mkdir "export"

mkdir "export/raymania_linux"
make "raymania.out"
cp "raymania.out" "export/raymania_linux/raymania.out"
cp "GAME_README.txt" "export/raymania_linux/README.txt"
cp -r "sounds" "export/raymania_linux/"
cp -r "tracks" "export/raymania_linux/"
cd "export"
7z a "raymania_linux_" "raymania_linux"
rm -rf "raymania_linux"
